const $ = selector => document.querySelector(selector);
const opening = $('#opening'), site = $('#site');
function enterSite() { opening.classList.add('hidden'); site.classList.remove('hidden'); }
setTimeout(enterSite, 5400); $('#skip').onclick = enterSite;
const no = $('#no'), hero = $('#hero'), date = $('#date'), time = $('#time'), slots = $('#time-slots'), next = $('#to-activities');
function dodge() { no.style.position = 'absolute'; no.style.left = `${Math.floor(Math.random() * Math.max(130, hero.clientWidth - 165))}px`; no.style.top = `${Math.floor(Math.random() * Math.max(150, hero.clientHeight - 80))}px`; $('#no-message').textContent = 'Кнопка «нет», как и ты, очень стеснительная.'; }
no.onmouseenter = dodge; no.onclick = dodge; no.ontouchstart = event => { event.preventDefault(); dodge(); };
$('#yes').onclick = () => { $('#hero').classList.add('hidden'); $('#planner').classList.remove('hidden'); $('#planner').scrollIntoView({ behavior: 'smooth' }); };
const dayNames = ['вс', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб'], monthNames = ['янв', 'фев', 'мар', 'апр', 'мая', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек'];
const iso = value => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`;
function hours(day) { return day === 0 ? [20, 21, 22, 23] : day === 1 ? [21, 22, 23] : [19, 20, 21, 22, 23]; }
function renderTimes() { const available = hours(new Date(`${date.value}T12:00`).getDay()); time.value = ''; slots.innerHTML = ''; next.disabled = true; $('#time-help').textContent = ''; available.forEach(hour => { const button = document.createElement('button'); button.type = 'button'; button.className = 'slot'; button.textContent = `${String(hour).padStart(2, '0')}:00`; button.onclick = () => { time.value = button.textContent; document.querySelectorAll('.slot').forEach(item => item.classList.remove('selected')); button.classList.add('selected'); next.disabled = false; }; slots.append(button); }); }
function buildDayPicker() { const picker = $('#day-picker'), cursor = new Date(); cursor.setHours(12, 0, 0, 0); cursor.setDate(cursor.getDate() + 1); let added = 0; while (added < 12) { if (cursor.getDay() !== 6) { const value = iso(cursor), button = document.createElement('button'); button.type = 'button'; button.className = 'day-chip'; button.dataset.date = value; button.innerHTML = `<span>${dayNames[cursor.getDay()]}</span><strong>${cursor.getDate()}</strong><small>${monthNames[cursor.getMonth()]}</small>`; button.onclick = () => { date.value = value; document.querySelectorAll('.day-chip').forEach(item => item.classList.toggle('selected', item === button)); renderTimes(); }; picker.append(button); added++; } cursor.setDate(cursor.getDate() + 1); } }
buildDayPicker();
next.onclick = () => { $('#step-time').classList.add('hidden'); $('#step-activity').classList.remove('hidden'); $('#progress-time').classList.remove('active'); $('#progress-activity').classList.add('active'); };
$('#back').onclick = () => { $('#step-activity').classList.add('hidden'); $('#step-time').classList.remove('hidden'); $('#progress-activity').classList.remove('active'); $('#progress-time').classList.add('active'); };
$('#date-form').onsubmit = event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); if (!data.activity) return; $('#step-activity').classList.add('hidden'); $('.planner-head').classList.add('hidden'); $('.steps').classList.add('hidden'); $('#success').classList.remove('hidden'); const pretty = new Date(`${data.date}T12:00`).toLocaleDateString('ru-RU', { weekday: 'long', day: 'numeric', month: 'long' }); $('#success-text').textContent = `${pretty}, ${data.time} · ${data.activity}${data.note ? ` · ${data.note}` : ''}.`; $('#success').scrollIntoView({ behavior: 'smooth' }); };
